### PR TITLE
Fix: Unable to start service on Bluestacks

### LINKED ISSUE #967: Unable to start service on Bluestacks
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1556

### Describe the bug

Whenever I click start service the "start now" button is unable to be pressed.

I have on compatibility mode as recommended (I searched up the issue and it seems the previous individual with this issue did not).

I recently uninstalled and reinstalled the app. It was working perfectly before, I've tried creating new instances of blue stacks and installing FGA there with no luck.

To replicate please download a fresh instance of FGA onto a blue stacks 32bit instance and try to start the service after giving the appropriate permissions.

### Video

Was not able to record as I was unable to start service
Capture

Here is an image to show the screen i'm stuck on. The "start service" button doesn't do anything however the cancel button works. When I exit the app after unsuccessfully starting the service I can see the play button flash on the bottom left corner sometimes.

### Device model

Samsung Galaxy S8 Plus (Bluestacks 32bit)

### Android version

7

### Screen size

1600x900

### RAM

2

### PR DESCRIPTION
**Pull request by MathewSachin**
fixes #967 

Added a message if fails to initialize screen capture, now there's a weird new bug:
If root is used on a non-rooted phone, dialog pops up. after turning off service, turning off root and turning on service, clicking on play causes a crash which looks like OpenCV memory got bugged somehow. Need to figure this out.

```
CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.4.0) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
    ]
        at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
        at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:5098)
        at com.mathewsachin.fategrandautomata.imaging.MediaProjectionScreenshotService.takeScreenshot(MediaProjectionScreenshotService.kt:48)
        at com.mathewsachin.libautomata.ScreenshotManager.getScaledScreenshot(ScreenshotManager.kt:25)
        at com.mathewsachin.libautomata.ScreenshotManager.snapshot(ScreenshotManager.kt:35)
        at com.mathewsachin.libautomata.ScreenshotManager.useSameSnapIn(ScreenshotManager.kt:64)
        at com.mathewsachin.libautomata.StandardAutomataApi.useSameSnapIn(StandardAutomataApi.kt:23)
        at com.mathewsachin.fategrandautomata.scripts.FgoAutomataApi.useSameSnapIn(Unknown Source:7)
        at com.mathewsachin.fategrandautomata.scripts.entrypoints.AutoDetect.useSameSnapIn(Unknown Source:7)
        at com.mathewsachin.fategrandautomata.scripts.entrypoints.AutoDetect.get(AutoDetect.kt:13)
        at com.mathewsachin.fategrandautomata.runner.ScriptManager.startScript(ScriptManager.kt:276)
        at com.mathewsachin.fategrandautomata.runner.ScriptRunnerOverlay.act(ScriptRunnerOverlay.kt:165)
        at com.mathewsachin.fategrandautomata.runner.ScriptRunnerOverlay.access$act(ScriptRunnerOverlay.kt:30)
        at com.mathewsachin.fategrandautomata.runner.ScriptRunnerOverlay$1$1.invoke(ScriptRunnerOverlay.kt:66)
        at com.mathewsachin.fategrandautomata.runner.ScriptRunnerOverlay$1$1.invoke(ScriptRunnerOverlay.kt:64)
        at com.mathewsachin.fategrandautomata.ui.runner.ScriptRunnerUIKt$ScriptRunnerUI$1$1$1$1.invoke(ScriptRunnerUI.kt:60)
        at com.mathewsachin.fategrandautomata.ui.runner.ScriptRunnerUIKt$ScriptRunnerUI$1$1$1$1.invoke(ScriptRunnerUI.kt:53)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:137)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:131)
        at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:378)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:432)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:330)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:343)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:287)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
        at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:151)
        at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:90)
        at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-gBdvCQM(PointerInputEventProcessor.kt:77)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:860)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3138)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
        at android.view.View.dispatchPointerEvent(View.java:14740)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6595)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6372)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5802)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5866)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5825)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6011)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5833)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6068)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5806)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5866)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5825)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5833)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5806)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8737)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8688)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8641)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8878)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:221)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:201)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8827)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8917)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1470)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1267)
        at android.view.Choreographer.doFrame(Choreographer.java:971)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1455)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:254)
        at android.app.ActivityThread.main(ActivityThread.java:8243)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

### CODE REVIEW

**Comment by Daynar100** [comment]
Is there an quick way to get an apk with this fix? Or should I just download the branch and try to make it myself?

**Comment by reconman** [comment]
Doesn't run on my Bluestacks 32 bit instance. Crashes when pressing the play button:
```
12-25 22:21:20.120 10544 10544 E AndroidRuntime: FATAL EXCEPTION: main
12-25 22:21:20.120 10544 10544 E AndroidRuntime: Process: com.mathewsachin.fategrandautomata.debug, PID: 10544
12-25 22:21:20.120 10544 10544 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.mathewsachin.fategrandautomata.runner.ScriptRunnerService: java.lang.IllegalStateException: Accessibility service not running
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3204)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at android.app.ActivityThread.-wrap5(ActivityThread.java)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6138)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
12-25 22:21:20.120 10544 10544 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Accessibility service not running
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at x4.a.<init>(HighlightManager.kt:18)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at h5.j$i$a.get(DaggerAutomataApplication_HiltComponents_SingletonC.java:22)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at q5.a.get(DoubleCheck.java:5)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at h5.j$i$a.get(DaggerAutomataApplication_HiltComponents_SingletonC.java:29)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at q5.a.get(DoubleCheck.java:5)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at h5.j$i$a.get(DaggerAutomataApplication_HiltComponents_SingletonC.java:54)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at q5.a.get(DoubleCheck.java:5)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at h5.j$i$a.get(DaggerAutomataApplication_HiltComponents_SingletonC.java:111)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at q5.a.get(DoubleCheck.java:5)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at h5.j$i.a(DaggerAutomataApplication_HiltComponents_SingletonC.java:1)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at h4.a.onCreate(Hilt_ScriptRunnerService.java:3)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at com.mathewsachin.fategrandautomata.runner.ScriptRunnerService.onCreate(ScriptRunnerService.kt:1)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3194)
12-25 22:21:20.120 10544 10544 E AndroidRuntime:        ... 8 more
12-25 22:21:20.120 10544 10544 I Process : Sending signal. PID: 10544 SIG: 9
12-25 22:21:20.172  1752  2218 I ActivityManager: Process com.mathewsachin.fategrandautomata.debug (pid 10544) has died
```

**Comment by MathewSachin** [comment]
> Unable to create service com.mathewsachin.fategrandautomata.runner.ScriptRunnerService: java.lang.IllegalStateException: Accessibility service not running

This looks unrelated to the changes though, try restarting accessibility service.

**Comment by reconman** [comment]
I have to force kill FGA if this happens and then restart Accessibility anyways.

After that, the same thing happens. Only switching to the last official release without these changes helped.

**Comment by MathewSachin** [comment]
I closed this PR and did a minor change for fix on master.

**Pull request closed without merging**
