### PR TITLE
Soujuurou/Charlotte/Hakunon/Van Gogh(Miner)/BB Dubai/Ptolemy

### LINKED ISSUE #1841: add sanjuurou 3ºskill options
### Preparation

- [X] No one has asked for this feature before in other issues (even the closed ones)

### Describe the feature

put a separate option for sanjurrou's 3rd skill, just like there is for Kukulkan, space ishtar, melucine etc...

### PR DESCRIPTION
**Pull request by ArthurKun21**
# Soujuurou/Charlotte/Hakunon/Van Gogh(Miner)/BB Dubai/Ptolemy

## Pull Request Type

- [ ] Bugfix
- [X] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

fixes #1841

## Description

Added the following servants to the Command Card System:
- Soujuurou
- Charlotte
- Hakunon
- Van Gogh(Miner)
- BB Dubai
- Ptolemy

---

Introduced new commands to handle future servants with unique skills.

Added the following commands:
- `[Ch3A]` - 3 Choices and Select A option.
- `[Ch3B]`- 3 Choices and Select B option.
- `[Ch3C]` - 3 Choices and Select C option.

All new special targets have special condition that one of the commands must not look like the starting string for another code

For Example

`[Ch3A]` -> 3 Choices and Select A option.

There should be no `[Ch3]` command, as having so will create problems when parsing. Already added checker on the code that will throw an error when run on device.

---

Updated the error message when manually entering skill command for more clarity

## Screenshots 

3 Choices

3 Choices of Soujuurou

---

New Command System in action `Choices (3)`

output_720p

---

Error Message when command does not exist

image

---

### Updated Look

Skill 1

image

Skill 2

image

Skill 3

image

---

#### Kukulkan

image

#### Emiya/BB Dubai

image

#### Hakunon/Charlotte/Soujuurou

image

#### Van Gogh (Miner)

image

#### Space Ishtar

image

#### Melusine/Ptolemy

HD-Player_CtUxHbPTDE

---

### Button Labels

Helps user to know what is the effect of the skill. Defaults to just generic option message.

#### Emiya/BB Dubai

HD-Player_kCHleHG6IY

#### Hakunon/Charlotte/Soujuurou

HD-Player_lSg6vJ3i4R

#### Van Gogh (Miner)

HD-Player_jly0BYqRGn

#### Kukulkan

HD-Player_dk1kl1I3UN

#### Space Ishtar

HD-Player_y6LnrQZsX4

### CODE REVIEW

**Comment by vybze** [comment]
I was thinking about replacing Emiya with Command Card Change (CCC) and then adding options for the different servants within this option

**Comment by oppaio** [comment]
when will this get implemented?

**Comment by vybze** [comment]
Screenshot_20240809-115638
Posting this here for reference

**Comment by vybze** [comment]
And another one for the list 
Untitled
Will add a better screenshot at a later date

**Comment by vybze** [comment]
Screenshot_20240916-235140
Better screenshot

**Comment by reconman** [comment]
What I've changed in my last commit:

- Add Summer Barghest's 3rd skill to the 2 choices options
- Also move "Choice (2)" to special targets
- Rename "Two Target" and "Three Target" to "NP Type (2)" and "NP Type (3)"
- Fix Skill Target UI for wide screen phones. Before, the No Target button would overlap the Servant ones.

Still needed:
- Rename some variables after the "Two Target" and "Three Target" change
- Optional: Convert the skill command in the builder to a more user-readable format. We only need the `[Ch3A]` text when parsing it and when users edit the command manually, but it's not needed for displaying the finished command.
- Testing
- Adjust Battle.md documentation

**Comment by vybze** [comment]
Why not name them special options instead of choices?

**Pull request merged**
