### PR TITLE
Add inventory full check function for fix logic

### PR DESCRIPTION
**Pull request by item4**
By this PR, FP Gacha scripts changes::

1. Can start already run cost-free FP, click position is move right little for cover free button and 2000 FP button both.
2. Can check inventory is full, and if inventory was full, exit script.
3. Use one loop logic instead one if and one while. It make easy to manage code.
4. Replace KR server `inven_full.png` file to grayscale.

### CODE REVIEW

**Comment by item4** [comment]
I think I choose wrong solution but it did not work fine. old version can not detect inventory full.

**Comment by reconman** [comment]
To avoid spam from commit pushes, could you please build and test the app locally with Android Studio? Right now, it doesn't even compile.

You only need to change one line in app/build.gradle:
```
versionCode Integer.valueOf(System.env.FGA_VERSION_CODE ?: 1)
```

Replace the `1` at the end with the version currently installed on your device.

**Comment by item4** [comment]
Yes I will

**Comment by item4** [comment]
@reconman Okay, I setup Android Studio on my Windows PC and build & test locally. But I cannot test Jp and En server. I updated description of this PR. please check is it right

**Comment by item4** [comment]
@reconman review please 🙏

**Comment by item4** [comment]
Close PR, I will remake that

**Pull request closed without merging**
