### PR TITLE
Use OCR for gift box detection

### LINKED ISSUE #1595: Gift Box EXP searching and clicking error or just broken ;(
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

2012

### Describe the bug

When i'm at 1x / 100x in lottery screen i get the Gift Box prompt to search and tap; seems like the giftbox is broken.
It also seems like it keeps prompting me into Gift Box prompt to search, even i'm on the normal screen (for battle nodes or friend gacha screen)

I think it broke when i shot that vid ... I managed to get it to work again by restarting the app. Then it broked again when i tried the 2nd video. The Battle and stuff is working at least.

Anyways, for my phone stuff... its Poco F3. I'm running a miui 12.5.19 by xiaomi.eu

### Video

https://youtu.be/ams2lMs5wvQ
https://youtu.be/4u3_b0hl8HM

### Device model

Poco F3

### Android version

12

### Screen size

2400x1080

### RAM

8GB

### PR DESCRIPTION
**Pull request by reconman**
Uses Tesseract OCR for parsing the ember count in the gift box.

Fixes #1595 #1558 #1009

### CODE REVIEW

**Comment by reconman** [comment]
@MetLee @item4 @the3dsandwich Can you test the feature on your game servers and also translate the new messages?

- picked_exp_stacks was changed to include the gold ember count
- p_max_gold_ember_total_count for the setting on how many 4* EXP cards should be collected in total

Additionally, I've updated p_skill_confirmation_onboarding_description recently because it caused confusion.

For CN and TW the following translations for recently added messages are still missing:
- update_download_success when the user triggers an in-app update
- support_imgs_extracting to inform the user that something is happening when the support images are extracted during onboarding

**Comment by item4** [comment]
I feel that needs test case for working correctly but there is no lottery event yet.

**Comment by MetLee** [comment]
I ended my vacation trip a few days ago, so I will translate them this week.

**Comment by MetLee** [comment]
updated some translations in poeditor

**Pull request merged**
