### PR TITLE
update TW localization

### PR DESCRIPTION
**Pull request by the3dsandwich**
continuing #1622

TW localization needs to be updated so this PR is the update. Some formatting is also done for previously translated texts (full width punctuation, add one space between full width and half width characters)

### CODE REVIEW

**Comment by reconman** [comment]
There are still about 40-50 untranslated strings, some related to Kukulcan, custom game area, and the new onboarding screens.

image

**Comment by reconman** [comment]
Still missing Kukulkan and the new onboarding strings:
image

**Comment by the3dsandwich** [comment]
Wait. I started my edit on an older version. Let me fix that

**Comment by reconman** [comment]
Already asked on Discord: can you translate "Donate" for a donate button while you're at it? Is it 捐款 ?

**Comment by the3dsandwich** [comment]
> Already asked on Discord: can you translate "Donate" for a donate button while you're at it? Is it 捐款 ?

Sure, let me do it now

**Comment by reconman** [comment]
You only need to provide the translated word, I'll do the rest of adding it to the localized.xml.

**Comment by the3dsandwich** [comment]
Oh okay was wondering why I can't find the text anywhere

yes it is 捐款

or the less formal 斗內

for the tone now I think 捐款 is better

**Pull request merged**
