### PR TITLE
Add betterfgo APK support

### PR DESCRIPTION
**Pull request by neobenedict**
Add modded FGO APK support by adding the two package names.

### CODE REVIEW

**Comment by the3dsandwich** [comment]
Dumb question but what is betterfgo?

I tried to google but can't seem to find immediate results

**Comment by neobenedict** [comment]
> 
> 
> Dumb question but what is betterfgo?
> 
> I tried to google but can't seem to find immediate results

The main purpose of the pull request is this mod is able to hook `UnityEngine.Screen::get_width()` and `UnityEngine.Screen::get_height()` to force the game's UI to 16:9 while keeping the game border-free. It just has a different package name to FGO.

You can find the mod in the Rayshift discord, it's not distributed widely.

**Comment by the3dsandwich** [comment]
I see. This sounds cool. Thanks for the info!

**Comment by MathewSachin** [comment]
> mod is able to hook UnityEngine.Screen::get_width() and UnityEngine.Screen::get_height() to force the game's UI to 16:9 

FGA started looking outside the 16:9 region from 4a8f68e2db97e00e12ebdbf5d9cff665d5a8c070 and right now is at a stage where wide-screen is kind of working (atleast on the few devices and resolutions I checked). See #571.

> Add modded FGO APK support by adding the two package names.

I'm personally against adding modded APK names into the app. I had denied a request before in https://github.com/Fate-Grand-Automata/FGA/issues/420#issuecomment-695158507 and I really sounded like an idiot there because I was mad at the influx of questions at that point.
That was when Max created a fork and I think he added BetterFGO there too.
If I add BetterFGO, I won't be able to deny adding other modded APK names as I did before. I don't want to track all the modded APK names that are gonna pop up here after that. Hope you understand.

------------------------------

As a solution, I'll think about adding back the option to set the Game Server manually, so that modded APK names don't need to be included. I'll keep its default to auto-detect while still allowing the user to change if needed.

**Comment by MathewSachin** [comment]
#643 adds back the Game Server option which can be changed in case you don't want the auto-detection. This can be used regardless of the APK package name.

**Pull request closed without merging**
