### PR TITLE
KR translations for AP regen

### PR DESCRIPTION
**Pull request by ScathachSkadi**
I am a noob on Github so I don't know how to make the master up to date and resolve conflicts. :(

### CODE REVIEW

**Comment by reconman** [comment]
1. Install the git command line tool from https://git-scm.com/download/win
2. Go to your cloned repository folder in Windows Explorer, Right Click in the background and choose "Git Bash Here"
3. Enter the following commands to reset your master branch:

```
git config --global user.name "ScathachSkadi"
git config --global user.email 70437676+ScathachSkadi@users.noreply.github.com
git remote add upstream https://github.com/Fate-Grand-Automata/FGA.git

git checkout master
git fetch upstream
git reset --hard upstream/master
git push -f
```

The steps before the empty line are only necessary the first time. The rest of the steps will completely replace your master branch, so make sure there's nothing you want to lose on your own master.

If you want to add commits from this repo's master to your master in the future (and don't have any of your own commits on it), do this:
```
git checkout master
git fetch upstream
git pull upstream master
git push
```

If you don't do it this way and instead use Github's Pull Request system, you will have lots of extra merge commits in your history.

**Comment by reconman** [comment]
@ScathachSkadi Can you check if I rewrote your branch correctly? I replaced all your commits with one of the several in this PR.

**Comment by ScathachSkadi** [comment]
@reconman I will try the commands. What do you mean by rewriting the branch?

**Comment by reconman** [comment]
@ScathachSkadi I overwrote your commit history. Now your PR only has 1 commit instead of 5 or 6.

**Comment by ScathachSkadi** [comment]
@reconman Oh that's what it means. Yes. It's correct. Thank you.

**Comment by ScathachSkadi** [comment]
@reconman After entering "git remote add upstream https://github.com/Fate-Grand-Automata/FGA.git"

it says  fatal: not a git repository (or any of the parent directories): .git

**Comment by reconman** [comment]
Did you clone your own repository and are you in that folder with Git Bash?

**Comment by ScathachSkadi** [comment]
@reconman I downloaded the zip and opened the Git bash in the folder after extracting the zip. Did I miss something?

**Comment by reconman** [comment]
That's not cloning, this is:
```
git clone https://github.com/ScathachSkadi/Fate-Grand-Automata.git
```

It will create a folder called "Fate-Grand-Automata" in the directory you're in with Git Bash. Delete your unzipped files first.

**Comment by ScathachSkadi** [comment]
@reconman Thanks. I think I got it working but after "git checkout master" it says: 
error: you need to resolve your current index first
app/src/main/res/values-ko/localized.xml: needs merge

**Comment by reconman** [comment]
That should not happen after a fresh clone.

I need a screenshot of Git Bash to be able to help you.

**Comment by ScathachSkadi** [comment]
@reconman I re-deleted everything and force closed git and redid everything from the start and it worked. Thank you so much! I will use this command whenever I need to make a translation PR. Thank you for helping a noob like me. 👍

**Pull request merged**
