### PR TITLE
Support New UI of KR server

### LINKED ISSUE #786: Application problem due to UI change of Korean server
Before opening an issue:
- [ check ] I tested the latest release
- [ check ] I looked at other issues (even the closed ones)
- [ check ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ check ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
First, I apologize for my poor English.
The application does not work properly as the Korean server's user interface becomes the same as the Japanese server.
There are problems such as the location of the touch and the inability to recognize it.

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Most devices (Author is using Galaxy 21)]
 - Screen size: [Most display sizes (Author's device display is 2400x1080)]
 - Android Version: [Most Android versions (Author is using Android 11)]
 - RAM: [Most Capacity (Author is using 8GB)]
 - Most Korean server users are experiencing this problem.

### PR DESCRIPTION
**Pull request by item4**
I can not check it is working correctly because I am not app developer.

For testing, merge and build on GitHub Actions

---

fix #786

### CODE REVIEW

**Comment by reconman** [comment]
Can you test the build yourself? https://github.com/Fate-Grand-Automata/FGA/suites/3328601476/artifacts/78016401

**Comment by kbg0104** [comment]
@reconman Based on Galaxy 21, there is still a problem that the location of the click on the battle screen and the friend selection is not in sync.

**Comment by kbg0104** [comment]
@reconman 
3 mp4_20210726_184708 031
4 mp4_20210726_184856 982
4 mp4_20210726_184905 950

**Comment by item4** [comment]
https://user-images.githubusercontent.com/559952/126970784-27bfd636-4f9c-44ac-b6db-197dd21c91af.mp4

touch 6th servent slot instead of quest start

I guess it is some wrong value of here: https://github.com/Fate-Grand-Automata/FGA/blob/732a831739a54e37c7e1fa35366c4353eb2464e4/scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/modules/Game.kt#L104-L105

**Comment by item4** [comment]
@kbg0104 canary 말고 app.zip 파일 받아보세요

**Comment by item4** [comment]
@reconman battle is fine. but first quest start is werid

**Comment by kbg0104** [comment]
@item4 위 스크린샷이 그걸로 테스트 해본겁니다. 디스플레이의 비율에 영향을 많이 받는것같군요. The above screenshot was tested using app.zip. It seems that the ratio of the display is greatly affected.

**Comment by item4** [comment]
@kbg0104 서버 한국 선택 하셨나요? 한국 선택하면 셀렉창에서 디버그가 저렇게 안 떠서요

**Comment by item4** [comment]
Finally I do run battle with this PR, and it is the settings:

1. Select KR server
2. Disable(uncheck) Ignore notch flag
3. Go to Android Preference > Display > Fullscreen Apps, and **turn off** FGO. (Do not use as fullscreen)
4. Turn off FGO completely.
5. Stop service and Turn off FGA completely.
6. Play it.

Note: Do not try take screen recording in using FGA. It break FGA sanity.

**Comment by MathewSachin** [comment]
@kgb you have black bars on both sides of the screen similar to #784. This build would only work if FGO covers the whole screen including the notch. I think you need to make FGO a full-screen app.

> touch 6th servent slot instead of quest start
I guess it is some wrong value of here:

@item4 Starting from the Party selection screen was never supported. It's clicking wrong because it can't detect which screen it is.

> 1. Select KR server

Does `Auto detect` not detect KR server now?

> 2. Disable(uncheck) Ignore notch flag

This has no effect. `IsNewUI` implies ignore notch.

https://github.com/Fate-Grand-Automata/FGA/blob/732a831739a54e37c7e1fa35366c4353eb2464e4/app/src/main/java/com/mathewsachin/fategrandautomata/util/CutoutManager.kt#L74-L75

> 3. Go to Android Preference > Display > Fullscreen Apps, and turn off FGO. (Do not use as fullscreen)

I would like to see the script running after turning this OFF. I believe this needs to be ON.

> Note: Do not try take screen recording in using FGA. It break FGA sanity.

Which is why there's an inbuilt recording feature in the app. Check More options/Advanced.

**Comment by item4** [comment]
> I would like to see the script running after turning this OFF. I believe this needs to be ON.
Yes I agree. Seperated usage guide make user painful. But i am not well knowing this environment such as android, kotlin and so on, and I can not run sainly with fullscreen flag. Just I guess android fullscreen settings make difference of screen resolution and dimension.

> Does Auto detect not detect KR server now?
Need to do test. but I have no AP now. I will try that after morning.

**Comment by MathewSachin** [comment]
> Yes I agree. Seperated usage guide make user painful. But i am not well knowing this environment such as android, kotlin and so on, and I can not run sainly with fullscreen flag. Just I guess android fullscreen settings make difference of screen resolution and dimension

I think there's a misunderstanding.
I meant to ask for a video showing the script running. You can record video from within FGA by turning it ON from More options/Advanced.

**Comment by MathewSachin** [comment]
@sleeping-player, @ScathachSkadi
Can you guys check if this build works: https://github.com/Fate-Grand-Automata/FGA/suites/3328601476/artifacts/78016401

**Comment by sleeping-player** [comment]
Ah, since I haven't done KR since the beginning of this year, it's difficult to test. I'm sorry for that.

**Comment by kbg0104** [comment]
@MathewSachin 
In Galaxy S21, there was only the same result as the screenshot above.
https://github.com/Fate-Grand-Automata/FGA/pull/787#issuecomment-886550289

All functions worked normally in Galaxy Note 9.
There was no problem choosing friends, dungeons, or consecutive dungeons that had previously been a problem.

**Comment by reconman** [comment]
@kbg0104 Please do this and share the video:

**Comment by kbg0104** [comment]
Everything is working normally.
The video was modified randomly due to its capacity. (Resizing and Cutting)

https://user-images.githubusercontent.com/36321971/127030941-863f4d51-09b9-486b-bd3e-c577e3cc71df.mp4

**Comment by MathewSachin** [comment]
@Yoshinyong Can you check the apk from this page: https://github.com/Fate-Grand-Automata/FGA/suites/3328601476/artifacts/78016401
Also, reset the stage counter similarity value for this build. Don't use 100% for this one.

**Comment by item4** [comment]
@MathewSachin I tested auto detect server and work fine

**Comment by item4** [comment]
I take video record but it is too huge to upload at GitHub.

There is no problem. But sometime area detect debug box placed wrong place.

(Check @kbg0104 's first upload video)

**Comment by ScathachSkadi** [comment]
@MathewSachin Sorry I am late. I tested the build by making the app full screen and it works perfectly. My device is S20+.

**Review by MathewSachin — APPROVED** [review]

**Pull request merged**
