### PR TITLE
CE bomb improvements by gary-stu

### PR DESCRIPTION
**Pull request by ArthurKun21**
the patch was here https://github.com/Fate-Grand-Automata/FGA/issues/998#issuecomment-1248435280 by gary-stu

### CODE REVIEW

**Comment by gary-stu** [comment]
Hey there,

Thanks for doing the PR for me!

Just for information, I did not test the code on the JP and CN versions of the game, only NA/english. 
I also only tested it on a non wide phone once.

I think I made a slight mistake in my previous patch on a isWide position (that still worked on my phone and seemingly yours too, but by chance).
On three different phones, the click wasn't exactly at the same position, so it could theorically miss on some phones.

Made this patch and tested on those three phones again, and it should be alright now
[Corrected_ceUpgradeOkButton_location_with_correct_position_(thought_it_was_x_from_center)_.patch.txt](https://github.com/Fate-Grand-Automata/FGA/files/9592038/Corrected_ceUpgradeOkButton_location_with_correct_position_.thought_it_was_x_from_center._.patch.txt)

Sorry and thanks again!

I'd also like your opinion on if the code was documented enough, so that other people could correct it if something went wrong after a FGO update or something

**Comment by potchy** [comment]
I did not read the code thoroughly, but I tested the APK and I have to say it works great. Way better than doing it manually.

**Comment by reconman** [comment]
Just FYI, I've been really stressed out by work and hobbies for 3 weeks, so I can't take a good look right now.

Might take a while until it gets merged.

**Comment by reconman** [comment]
Closing, continuing in #1545

**Pull request closed without merging**
