### PR TITLE
Improvements for common user errors

### PR DESCRIPTION
**Pull request by reconman**
- Onboarding screens for battery optimization, support images, skill confirmation, youtube
- Autoremove l command when using order swap afterwards
- Use return button instead of click in top right for Servant info windows

The return button can't be used if there are optional windows since it will ask the user if they want to withdraw from the quest.

### CODE REVIEW

**Comment by reconman** [comment]
@item4 @ScathachSkadi @the3dsandwich @MetLee Please translate the changed texts in localized.xml.

@the3dsandwich TW is especially outdated. You'll have to look through the history of the English localized.xml because I also changed some existing English texts like accessibility_disabled_message.

**Comment by MetLee** [comment]
sure

**Comment by the3dsandwich** [comment]
@reconman I'm on TW translation, but I'm not sure what **Thresholded stage counter detection (p_thresholded_stage_counter) **does, would you mind letting me know where I can look for what it does? CN translation mentions using binary pictures to detect stage number, but I'm still kind of confused

**Comment by reconman** [comment]
@the3dsandwich Check here for an explanation: https://github.com/Fate-Grand-Automata/FGA/pull/1243

**Comment by reconman** [comment]
Merging now, will add translations later through separate PRs.

**Pull request merged**
