### PR TITLE
Pull Request triggered from POEditor

### PR DESCRIPTION
**Pull request by reconman**
Pull Request triggered from POEditor

### CODE REVIEW

**Comment by reconman** [comment]
@item4 You wanted to review the translations. Any update?

**Comment by item4** [comment]
need some fix. may i make update at poeditor or comment at gh?

**Comment by item4** [comment]
I make update at poeditor

**Comment by item4** [comment]
@reconman please update this pr fetching new data from poeditor

**Comment by reconman** [comment]
Done

**Review by item4 — APPROVED** [review]
Korean is ok

**Pull request merged**
