### PR TITLE
Auto-detect skill confirmation

### PR DESCRIPTION
**Pull request by reconman**

### CODE REVIEW

**Comment by reconman** [comment]
@MetLee Can you provide a screenshot of Skill Confirmation like this?

**Comment by MetLee** [comment]
I have no Android phone with me right now, and my emulator on my laptop sometimes doesn't work correctly (but it works well on my workstation). So I need some time to fix the emulator......

BTW the CN server currently under maintenance until 7pm CST (UTC+8) for the summer event lol.

**Comment by reconman** [comment]
@skyio @dateyanai @memphise @NepPure Maybe you can help?

**Comment by reconman** [comment]
Got everything now, newest build should work for all servers.

**Pull request merged**
